openapi: 3.0.1
info:
  title: Wikipedia Plugin
  description: A plugin that allows the user interact with Wikipedia.
  version: 'v1'
servers:
  - url: https://chrisalbon-bug-free-journey-ppw6pxxrprc665-5003.preview.app.github.dev/
paths:
    /search:
        get:
            operationId: getArticles
            summary: Takes a question and searches Wikipedia for articles that might have the answer to that question, gets the full text of the wikipedia articles, then gives it to ChatGPT which tries to find the answer using only the contents of those articles.
            parameters:
                - in: query
                  name: query
                  schema:
                      type: string
                  description: Used to as a search term to find relevant articles on Wikipedia
            responses:
                "200":
                    description: OK